require 'fileutils'
require 'rubygems'
require 'fileutils'

# utility functions for manipulating environment variables
def set_env(key, value)
  if false == value
    value = 'FALSE'
  elsif true == value
    value = 'TRUE'
  end
  ENV[key.to_s.upcase] = value
end

def get_env(key)
  val = ENV[key.to_s.upcase]
  if 'FALSE' == val
    val = false
  elsif 'TRUE' == val
    val = true
  end
  val
end

task :default => [:clean, :build]

desc "Cleans the project"
task :clean => [:clean_screenshots] do
  directories_to_delete = [
      "./bin",
      "./obj",
      "./screenshots",
      "./test_servers",
      "./testresults.html"
  ]

  directories_to_delete.each { |x|
    rm_rf x
  }
end

task :build => [:build_android, "build_ios"] do

end

desc "Delete the existing screen shots and calabash reports."
task :clean_screenshots do

  directories_to_delete = [
      "./screenshots/",
  ]

  directories_to_delete.each { |directory|
    rm_rf directory
  }
end

desc "Compiles a Release version of the project for Android."
task :build_android => [:clean] do
  `/usr/bin/xbuild /t:SignAndroidPackage /p:Configuration=Release ./Tasky.Droid/Tasky.Droid.csproj`
end

desc "Compiles the project for iOS"
task :build_ios => [:clean] do
  `/Applications/Xamarin\\ Studio.app/Contents/MacOS/mdtool -v build "--configuration:Debug|iPhone" TaskyPro.sln`
  `/Applications/Xamarin\\ Studio.app/Contents/MacOS/mdtool -v build "--configuration:Debug|iPhoneSimulator" TaskyPro.sln`
end
